from arx.logs import LogError


def test_log_error():
    LogError("Test")
